[package]
name = "consensus-engine"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.2"


[lib]
name = "consensus_engine"
path = "src/lib.rs"


[lints.clippy]
pedantic = {level = "warn", priority = -1}
unwrap_used = "deny"

[lints.rust]
missing_docs = "warn"